version: '1.0'
name: pipeline-20260505
displayName: 自动构建Tauri应用
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
    tags:
      prefix:
        - v
variables:
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  TAURI_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
agent:
      shell: bash
stages:
  - name: stage-build
    displayName: Windows构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: build_app
        displayName: 构建应用
        schedulerType: DISTRIBUTED
        hostGroupID:
          ID: ybkauto
          hostID:
            - dac47c19-2f7d-436d-8f56-fbac09cb0306
        scriptType: batch
        script:
          - yarn install
          - yarn tauri build
          - echo '正常运行'
        gitClone: true
        notify: []
        strategy:
          retry: '0'
